// SPDX-License-Identifier: unlicensed
pragma solidity 0.8.28;

/**
 * @title IVerifier
 * @dev Generic interface for ZK proof verifier contracts.
 * Actual verifier contracts generated by Noir will have specific function signatures
 * for their respective proofs.
 */
interface IVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}